version: 2
jobs:
  install:
    working_directory: /var/www/html
    docker:
      - image: php:7.1-cli
    steps:
      - checkout
      - run:
          name: Install system packages
          command: apt-get update && apt-get -y install git zip unzip php7.1-zip
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version
      - run:
          name: Install project dependencies
          command: php composer.phar install
      - save_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
          paths:
            - vendor
  test_php-7.1:
    working_directory: /var/www/html
    docker:
      - image: php:7.1-cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "composer.json" }}
      - run:
          name: Unit
          command: vendor/bin/phpunit
  test_php-7.2:
    working_directory: /var/www/html
    docker:
      - image: php:7.2-cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "composer.json" }}
      - run:
          name: Unit
          command: vendor/bin/phpunit
  test_php-7.3:
    working_directory: /var/www/html
    docker:
      - image: php:7.3-cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "composer.json" }}
      - run:
          name: Unit
          command: vendor/bin/phpunit
  test_php-7.4:
    working_directory: /var/www/html
    docker:
      - image: php:7.4-rc-cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "composer.json" }}
      - run:
          name: Unit
          command: vendor/bin/phpunit
workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - test_php-7.1:
          requires:
            - install
      - test_php-7.2:
          requires:
            - install
      - test_php-7.3:
          requires:
            - install
      - test_php-7.4:
          requires:
            - install
